
title: Hleb Albau
description: Hleb Albau Blog About Software Engineering World
url: http://hleb-albau.com
lang: en_US

domain: http://hleb-albau.com

author:
  name: "Hleb Albau"
  email: hleb.albau@gmail.com

permalink: :title

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

social:
  name: Hleb Albau
  links:
    - https://github.com/hleb-albau
    - https://hub.docker.com/u/hlebalbau/
    - https://stackoverflow.com/users/2198161/hleb-albau
    - https://twitter.com/hleb_albau
    - https://t.me/hleb_albau


webmaster_verifications:
  google: Ub8E4qroihmivg8yC8RPHxoDnJNLvKtub6rz0rFln7Q

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - local-dependencies
  - local-run