### your site title here

title: Hleb Albau Personal Blog

excerpt_separator: "<!--excerpt-->"

sass: 
    style: compressed

# Google Analytics Tracker
analytics: UA-112936964-1

exclude:
- README.md