
title: Hleb Albau Personal Blog
url: "http://hleb-albau.com"

author:
  name: "Hleb Albau"
  email: hleb.albau@gmail.com

permalink: :year/:month/:day/:title
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - local-dependencies
  - local-run